### ISSUE TITLE
Error when bot key has no funds.

### ISSUE THREAD

**Issue by jordanmack** [ickb/stack#2]
![20240219200924](https://github.com/ickb/stack/assets/37931/da5e7e1b-455b-4b7b-a7b6-0b40a57d6948)

**Comment by phroi** [comment]
Sorry, I guess there were just not enough funds in the funding address to fund the bot, so there were less than 1M CKB plus mining fees. Then again, the funding feature was only meant for devnet, that's why I moved it to the deploy utility with the following commits:

- https://github.com/ickb/v1-bot/commit/346d8e42c9040421dceba6099d6a163a53077ceb
- https://github.com/ickb/v1-core/commit/751e4c7942ca93cc84d73ab4bd1e22897c377cb6
