### ISSUE TITLE
Funds not pulling from funding key.

### ISSUE THREAD

**Issue by jordanmack** [ickb/stack#3]
My bot key has 10k CKB and the funding key has 1m CKB. After 10 minutes, the following output is still on the screen:

CKB : 10000 + 0
ICKB: 0 + 0

Here are my testnet keys for reference if you need to debug.

BOT_PRIVATE_KEY=0x3a166293f466cfaadc4ea7935d878c1b279d83ea1daacc8a76e2e5e64720fca8 #ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf76dahct9rrku3nhjfpq2x48a78q04c8sylldjp
FUNDING_PRIVATE_KEY=0xb30065844ba8784200e712f1f6ba0e5567008186f78b036fdf0633c594cc36f8 #ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0vhgfguk5snrx9k5vrs0qyx7ak0huejdsrhx5wf

**Comment by phroi** [comment]
Well noted, sorry about that! The funding is not smart, it only activates if there are exactly **zero** funds. Adding funds while the bot is matching orders was never its intended usage as it would make difficult to understand if the bot is losing or gaining money. Also the funding feature was only meant for `devnet`, that's why I moved it to the `deploy` utility with the following commits:

- https://github.com/ickb/v1-bot/commit/346d8e42c9040421dceba6099d6a163a53077ceb
- https://github.com/ickb/v1-core/commit/751e4c7942ca93cc84d73ab4bd1e22897c377cb6

I would suggest using your testnet `FUNDING_PRIVATE_KEY` as `BOT_PRIVATE_KEY` since it already has the correct balance.

These suggestions should fully solve your issue, so I'm closing this. Feel free to re-open the issue if you feel your concerns have not been properly addressed! :pray:
