### ISSUE TITLE
Too many RPC calls

### ISSUE THREAD

**Issue by sfsf332** [ickb/stack#7]
this getHeadersByNumber Method causes too many RPC calls。 Are there any alternatives?

**Comment by phroi** [comment]
Hey @sfsf332, thank you for publicly expressing your interest in iCKB as part of the integration of iCKB in NervDAO, I personally appreciate a lot!! 🙏

> this getHeadersByNumber Method causes too many RPC calls

Not to disregard your expertise, but in my codebase exists only a single call to `getHeaderByNumber` that is [both cached and batched](https://github.com/ickb/v1-interface/blob/2656ef88989e6f33bb35ffdf5add30d0ef035881/src/queries.ts#L322-L354). This way a single header is never fetched more than a single time per session. Also only 12 iCKB deposits exist on mainnet, so not that many headers to fetch.

> Are there any alternatives?

No, not really, but I can suggest some improvements to [your codebase](https://github.com/ckb-devrel/nervdao/commit/3144c15d72bb2c651edd813a9164fd8829289e36): **start caching those `getHeaderByNumber` calls!!**

```
user@host:~/nervdao$ grep --recursive --line-number -i 'getheaderbynumber' .
./src/cores/queries.ts:444:        batch.add("getHeaderByNumber", blockNum);
./src/cores/queries.ts:496:        const header = await signer.client.getHeaderByNumber(tx.blockNumber);
./src/cores/queries.ts:525:        const header = await signer.client.getHeaderByNumber(tx.blockNumber);
./src/cores/queries.ts:556:        const header = await signer.client.getHeaderByNumber(tx.blockNumber);
./src/app/components/DashboardProfile.tsx:51:        const past = await signer.client.getHeaderByNumber(
./src/app/components/IckbStatus.tsx:24:        const past = await signer.client.getHeaderByNumber(
```

Additionally, I would like to suggest that this cache should not be implemented in the DApp, but in CCC itself. This way all DApps using CCC can get this for free. You should also evaluate which other RPC calls can be cached safely.

Love & Peace, Phroi

**Comment by phroi** [comment]
This DApp uses the RPC as sparingly as possible. Since we are talking about this, I'd like to document here the current network behaviors:

1. [Preloading](https://github.com/ickb/v1-interface/blob/2228895362204cc3827395fcbe9b9429781e01d5/src/main.tsx#L38), before entering the React App
2. [Re-fetching](https://github.com/ickb/v1-interface/blob/2228895362204cc3827395fcbe9b9429781e01d5/src/queries.ts#L37) all data ([except the data that we want to cache](https://github.com/ickb/v1-interface/blob/2228895362204cc3827395fcbe9b9429781e01d5/src/queries.ts#L269-L354)) every 10 minutes or, if an order is pending, every one minute
3. [Checking tx status](https://github.com/ickb/v1-interface/blob/2228895362204cc3827395fcbe9b9429781e01d5/src/Action.tsx#L121) every ten seconds when awaiting tx confirmation, after confirmation [force recheck of all data](https://github.com/ickb/v1-interface/blob/2228895362204cc3827395fcbe9b9429781e01d5/src/Action.tsx#L131) (except as before)
4. If all data is older than 10 seconds and user needs to create a tx, user needs to manually click to [refresh all data](https://github.com/ickb/v1-interface/blob/2228895362204cc3827395fcbe9b9429781e01d5/src/Action.tsx#L62-L67) (except as before)

Closing the issue for now, feel free to reopen it :hugs:

Love & Peace, Phroi
